# Generated by Django 5.2 on 2025-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
                ('title', models.CharField(default='Біз туралы', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('button_text', models.CharField(default='Толығырақ хабарлығы', max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcement_images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='announcement_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='announcement_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='announcement_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='announcement_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='announcement_images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='announcement_images/')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('button_text', models.CharField(default='Толығырақ', max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='club_images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='club_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='club_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='club_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='club_images/')),
                ('title', models.CharField(max_length=200, verbose_name='Название клуба')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('button_text', models.CharField(default='Толығырақ', max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('working_hours', models.CharField(max_length=200, verbose_name='Часы работы')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('whatsapp_url', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('map_iframe', models.TextField(verbose_name='Iframe код карты')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(max_length=200, verbose_name='Текст копирайта')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футеры',
            },
        ),
        migrations.CreateModel(
            name='ITDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='IT бағыты', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'IT направление',
                'verbose_name_plural': 'IT направления',
            },
        ),
        migrations.CreateModel(
            name='ManagementMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='management_images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='management_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='management_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='management_images/')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('button_text', models.CharField(default='Толығырақ', max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Член управления',
                'verbose_name_plural': 'Члены управления',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('main_title', models.CharField(max_length=200, verbose_name='Основной заголовок')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Подзаголовок')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название технологии')),
                ('css_class', models.CharField(help_text="Например, 'html', 'css', 'python'", max_length=50, verbose_name='CSS класс')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.CreateModel(
            name='ITCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='it_course_images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='it_course_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='it_course_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='it_course_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='it_course_images/')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('button_text', models.CharField(default='Толығырақ', max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('technologies', models.ManyToManyField(to='main.technology', verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'IT курс',
                'verbose_name_plural': 'IT курсы',
            },
        ),
    ]
