# Generated by Django 5.2 on 2025-05-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_slider_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='full_description',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='club',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='itcourse',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='managementmember',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
