# Generated by Django 5.2 on 2025-05-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_slider_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='club',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='itcourse',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='managementmember',
            name='additional_info',
        ),
        migrations.AlterField(
            model_name='contact',
            name='working_hours',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Часы работы'),
        ),
    ]
