# Generated by Django 5.2 on 2025-05-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_aboutus_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementmember',
            name='button_text',
            field=models.CharField(blank=True, default='Толығырақ', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
    ]
